home/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('<int:id>/<slug:slug>/', views.service_detail, name='service_detail'),

]\
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'portfolio'

urlpatterns = [
    path('', views.portfolio_list, name='portfolio_list'),
    path('<int:id>/<slug:slug>/', views.portfolio_detail, name='portfolio_detail'),
]\
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

teplotron_kursk/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('news/', include('news.urls', namespace='news')),
    path('about_us/', include('about_us.urls', namespace='about_us')),
    path('portfolio/', include('portfolio.urls', namespace='portfolio')),
    path('summernote/', include('django_summernote.urls')),
    # path('', include('about_us.urls', namespace='about_us')),
]\
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import MinValueValidator, MaxValueValidator
from django.urls import reverse


class Portfolio(models.Model):
    name = models.CharField(max_length=200, db_index=True, verbose_name='Название выполненного объекта')
    slug = models.SlugField(max_length=200, db_index=True, verbose_name='Слаг')
    image = models.ImageField(upload_to='portfolio_avatar/%Y/%m/%d', blank=True, verbose_name='Аватар объекта')
    # tittle = models.TextField(max_length=512, blank=True, verbose_name='Заголовок')
    # position = models.IntegerField(default=None, blank=True, null=True, validators=[MinValueValidator(0), MaxValueValidator(20)], verbose_name='Позиция')
    description = models.TextField(max_length=10000, blank=True, verbose_name='Описание работ')
    available = models.BooleanField(default=False, verbose_name='Актуальность')
    created = models.DateField(blank=True, null=True, default=timezone.now, verbose_name='Дата создания записи')
    updated = models.DateField(blank=True, null=True, default=timezone.now, verbose_name='Дата ред-ия записи')

    class Meta:
        ordering = ('created', 'name')
        index_together = (('id', 'slug'),)
        verbose_name = 'Объект'
        verbose_name_plural = 'Объекты'

    def __str__(self):
        return '%s' % self.name

    def get_absolute_url(self):
        return reverse('portfolio:portfolio_detail', args=[self.id, self.slug])


class PortfolioDetails(models.Model):
    portfolio = models.ForeignKey(Portfolio, blank=True, null=True, default=None, on_delete=models.CASCADE,
                                  verbose_name='Объект')
    image = models.ImageField(upload_to='portfolios/%Y/%m/%d', blank=True, verbose_name='Доп. фото')
    available = models.BooleanField(default=True, blank=True, null=True, verbose_name='Активный?')
    created = models.DateField(blank=True, null=True, default=timezone.now, verbose_name='Дата создания записи')
    updated = models.DateField(blank=True, null=True, default=timezone.now, verbose_name='Дата ред-ия записи')

    def __str__(self):
        return '%s' % self.portfolio

    class Meta:
        verbose_name = 'Подробная информация к объекту'
        verbose_name_plural = 'Подробная информация к объекту'

portfolio/views.py
from django.shortcuts import render, get_object_or_404
from .models import Portfolio, PortfolioDetails
from services.models import Service
from about_us.models import AboutUs
from documentations.models import Document
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect


def portfolio_detail(request, id, slug):
    services = Service.objects.filter(available=True)
    portfolios = Portfolio.objects.filter(available=True)
    portfolio = get_object_or_404(Portfolio, id=id, slug=slug, available=True)
    about_us = AboutUs.objects.filter(available=True)
    documents = Document.objects.filter(available=True)
    return render(request, 'portfolio/portfolio_detail.html', {'portfolio': portfolio,
                                                               'portfolios': portfolios,
                                                               'services': services,
                                                               'about_us': about_us,
                                                               'documents': documents,
                                                               })


def portfolio_list(request):
    portfolio = Portfolio.objects.filter(available=True)
    services = Service.objects.filter(available=True)
    about_us = AboutUs.objects.filter(available=True)
    portfolios = Portfolio.objects.filter(available=True)
    documents = Document.objects.filter(available=True)
    # portfolio_images = PortfolioDetails.objects.filter(available=True, portfolio__available=True)
    return render(request, 'portfolio/portfolio_list.html', {'about_us': about_us,
                                                             'services': services,
                                                             'portfolio': portfolio,
                                                             'portfolios': portfolios,
                                                             # 'portfolio_images': portfolio_images,
                                                             'documents': documents,
                                                             })

templates/portfolio/portfolio_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ portfolio.name|truncatechars:30 }}{% endblock %}

{% block content %}
<main>
<!-- slider Area Start-->
<div class="slider-area ">
    <div class="single-slider hero-overly slider-height2 d-flex align-items-center" data-background="{{ portfolio.image.url }}">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="hero-cap pt-100">
{#                        <h2>{% if portfolio %}{{ portfolio.name }}{% else %}Галлерея{% endif %}</h2>#}
                        <nav aria-label="breadcrumb ">
                            <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="{% url 'home:home' %}">Домой</a></li>
                            <li class="breadcrumb-item"><a>{{ portfolio.name }}</a></li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- slider Area End-->

<!-- Project Area Start -->
    <section class="project-area  pt-55">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <!-- Nav Card -->
                    <div class="tab-content active" id="nav-tabContent">
                        <!-- card ONE -->
                        <div class="tab-pane fade active show" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
                            <div class="project-caption">
                                <div class="row">
                                    {% for p in portfolio.portfoliodetails_set.all %}
                                        <div class="col-lg-4 col-md-6">
                                            <div class="single-project mb-30">
                                                <div class="project-img">
                                                    <img src="{{ p.image.url }}" alt="">
                                                </div>
                                            </div>
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                <!-- End Nav Card -->
                </div>
            </div>
        </div>
    </section>
    <!-- Project Area End -->

    <!-- Services Details Start -->
    <div class="services-details-area">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="single-services mb-55">
                        <div class="details-caption">
                            {% if portfolio.description %}
                                <p>{{ portfolio.description }}</p>
                            {% endif %}
                            <h3>Остались вопросы?</h3>
                            <p>Позвоните нам или свяжитесь с нами по почте. Мы всегда рады Вам! Наши специалисты предлагают Вам сотрудничество по оказанию услуг в сфере обслуживания, проектирования, монтажа, строительства блок-модульных котельных под ключ, строительства инженерных сетей, наружных и внутренних газопроводов, пуско-наладочных работ теплотехнического и газоиспользующего оборудования, ремонт и замена устаревшего оборудования котельных, ЦТП, инженерных сетей.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Services Details End -->
</main>
{% endblock %}

templates/portfolio/portfolio_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Теплотрон | Портфолио{% endblock %}

{% block content %}

<main>
    <!-- slider Area Start-->
    <div class="slider-area ">
        <div class="single-slider hero-overly slider-height2 d-flex align-items-center" data-background="{% static 'working/img/hero/h1_hero.jpg' %}">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12">
                        <div class="hero-cap pt-100">
{#                            <h2>Портфолио</h2>#}
                            <nav aria-label="breadcrumb ">
                                <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{% url 'home:home' %}">Домой</a></li>
                                <li class="breadcrumb-item"><a>Объекты</a></li>
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- slider Area End-->

    <!-- Project Area Start -->
    <section class="project-area  section-padding30">
        <div class="container">
            <div class="project-heading mb-35">
                <div class="row align-items-end">
                    <div class="col-lg-6">
                        <!-- Section Tittle -->
                        <div class="section-tittle section-tittle3">
                            <div class="front-text">
                                <h2 class="">Наши проекты</h2>
                            </div>
                            <span class="back-text">Галлерея</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <!-- Nav Card -->
                    <div class="tab-content active" id="nav-tabContent">
                        <!-- card ONE -->
                        <div class="tab-pane fade active show" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
                            <div class="project-caption">
                                <div class="row">
                                    {% for g in portfolios %}
                                        <div class="col-lg-4 col-md-6">
                                            <div class="single-project mb-30">
                                                <div class="project-img">
                                                    <img src="{% if g.image %}{{ g.image.url }}{% else %}
        {% static "working/img/team/no_image_available.jpg" %}{% endif %}" alt="">
                                                </div>
                                                <div class="project-cap">
                                                    <a href="{{ g.get_absolute_url }}" class="plus-btn"><i class="ti-plus"></i></a>
                                                    <h4><a href="{{ g.get_absolute_url }}">{{ g.name }}</a></h4>
                                                    <h5><a href="{{ g.get_absolute_url }}">{{ g.description|truncatechars:70 }}</a></h5>
                                                </div>
                                            </div>
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                <!-- End Nav Card -->
                </div>
            </div>
        </div>
    </section>
    <!-- Project Area End -->
</main>
{% endblock %}