about_us/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'about_us'

urlpatterns = [
    path('', views.about, name='about_us'),
    path('contact/', views.contact, name='contact'),
]\
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('<int:id>/<slug:slug>/', views.service_detail, name='service_detail'),

]\
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'news'

urlpatterns = [
    path('', views.news_list, name='news_list'),
    path('<int:id>/<slug:slug>/', views.news_detail, name='news_detail'),
]\
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'portfolio'

urlpatterns = [
    path('', views.portfolio_list, name='portfolio_list'),
    path('<int:id>/<slug:slug>/', views.portfolio_detail, name='portfolio_detail'),
]\
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

teplotron_kursk/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('news/', include('news.urls', namespace='news')),
    path('about_us/', include('about_us.urls', namespace='about_us')),
    path('portfolio/', include('portfolio.urls', namespace='portfolio')),
    path('summernote/', include('django_summernote.urls')),
    # path('', include('about_us.urls', namespace='about_us')),
]\
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/navbar/navbar.html
{% load static %}

<header>

    <!-- Navbar_teplotron -->
   <div class="header-area header-transparent">
        <div class="main-header ">
            <div class="header-top d-none d-lg-block">
               <div class="container-fluid">
{#                   <div class="col-xl-12">#}
                        <div class="row d-flex justify-content-between align-items-center">
                            <div class="header-info-left">
                                <a href="{% url 'home:home' %}" class="big-logo"><img src="{% static 'working/img/logo/main_logo_final350.png' %}" alt=""></a>
                            </div>
{#                            <div class="header-info-left">#}
{#                                {% for a in about_us %}#}
{#                                    <ul>#}
{#                                        <li>{{ a.phone }}</li>#}
{#                                        <li>{{ a.email }}</li>#}
{#                                        <li>Пн - Сб: {{ a.schedule_start|time:'H:i' }} - {{ a.schedule_end|time:'H:i' }}, Вс - ЗАКРЫТО</li>#}
{#                                    </ul>#}
{#                                {% endfor %}#}
{#                            </div>#}
                            <div class="header-info-right">
                                {% for a in about_us %}
                                    <ul class="text-right">
                                        <li>{{ a.phone }}</li>
                                        <li>{{ a.email }}</li>
                                        <li>Пн - Сб: {{ a.schedule_start|time:'H:i' }} - {{ a.schedule_end|time:'H:i' }}, Вс - ЗАКРЫТО</li>
                                    </ul>
                                {% endfor %}
                            </div>
                        </div>
{#                   </div>#}
               </div>
            </div>
           <div class="header-bottom  header-sticky">
                <div class="container-fluid">
                    <div class="row align-items-center">
                        <div class="col-xl-9 col-lg-8 col-md-8">
                            <!-- Main-menu -->
                            <div class="main-menu f-left d-none d-lg-block">
                                <nav>
                                    <ul id="navigation">
{#                                        {% if user.is_superuser %}#}
{#                                            <li><a href="/admin/">Программа</a></li>#}
{#                                        {% endif %}#}
                                        <li><a href="{% url 'home:home' %}">Главная</a></li>
                                        <li><a>Услуги</a>
                                            <ul class="submenu">
                                                {% for s in services %}
                                                    <li><a href="{{ s.get_absolute_url }}">{{ s.name }}</a></li>
                                                {% endfor %}
                                            </ul>
                                        </li>
                                        <li><a>Лицензии</a>
                                            <ul class="submenu">
                                                {% for d in documents %}
                                                    <li><a href="{{ d.mention }}" target="_blank">{{ d.name }}</a></li>
                                                {% endfor %}
                                            </ul>
                                        </li>
                                        <li><a href="{% url 'portfolio:portfolio_list' %}">Объекты</a></li>
                                        <li><a href="{% url 'news:news_list' %}">Новости</a>
                                        <li><a href="{% url 'about_us:contact' %}">Контакты</a></li>
                                        <li><a href="{% url 'about_us:about_us' %}">О компании</a></li>
                                    </ul>
                                </nav>
                            </div>
                        </div>
                        <!-- Logo -->
                        <div class="col-xl-1 col-lg-2 col-md-1">
                            <div class="logo">
                                <!-- logo-1 -->
{#                                <a href="{% url 'home:home' %}" class="big-logo"><img src="{% static 'working/img/logo/main_logo.png' %}" alt=""></a>#}
                                <!-- logo-2 -->
                                <a href="{% url 'home:home' %}" class="small-logo"><img src="{% static 'working/img/logo/main_logo_final200.png' %}" alt=""></a>
                            </div>
                        </div>
                        <div class="col-xl-2 col-lg-2 col-md-3">
                            <div class="header-right-btn f-right d-none d-lg-block">
                                <a href="{% url 'about_us:contact' %}" class="btn">Обратная связь</a>
                            </div>
                        </div>
                        <!-- Mobile Menu -->
                        <div class="col-12">
                            <div class="mobile_menu d-block d-lg-none"></div>
                        </div>
                    </div>
                </div>
           </div>
        </div>
   </div>
</header>